site_name: Voyager
repo_name: Voyager
repo_url: https://github.com/Jodenee/Discohook

theme:
  name: material
  logo: assets/images/Voyager_Logo.svg
  favicon: assets/images/Voyager_Logo.svg
  language: en 

  icon:
    repo: fontawesome/brands/github

    admonition:
      warning: octicons/alert-16
      info: material/information-outline
      tip: fontawesome/regular/lightbulb
      note: material/notebook-edit-outline

  palette:
    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: custom
      accent: custom

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dark
      primary: custom
      accent: custom

      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  features:
    - content.code.copy

extra_css:
  - assets/stylesheets/theme.css

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Jodenee/Discohook
      name: Voyager on GitHub
    - icon: simple/roblox
      link: https://www.roblox.com/library/12390338563
      name: Voyager on Roblox
    - icon: simple/robloxstudio
      link: https://devforum.roblox.com/t/2188593
      name: Voyager on the devforum
    - icon: material/forum
      link: https://devforum.roblox.com/u/jodenewastaken
      name: Jodene on the devforum
  version:
    provider: mike