[package]
authors = ["Jodene"]
name = "jodenee/voyager"
description = "A Discord webhook API wrapper for Roblox."
license = "MIT"
version = "3.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
include = [
    "src", 
    "default.project.json", 
    "LICENSE",
    "wally.toml"
]
exclude = [
    "aftman.toml", 
    "docs",  
    "examples", 
    "mkdocs.yml", 
    "README.md",
    "CONTRIBUTING.md",
    "dev_env.project.json",
    "site",
    "*.rbxlx",
    "*.rbxl",
    "*.rbxmx",
    "*.rbxm",
    "*.zip"
]


[dependencies]
