name: Deploy documentation (release)

on:
  release:
    types: [published]

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install mike==2.0.0 mkdocs-material==9.5.7

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy documentation
        run: |
          mike deploy ${{ github.event.release.tag_name }} latest --update-aliases --push